### ISSUE TITLE
bullets everywhere after toggling game options

### ISSUE THREAD

**Issue by a-qxin** [park-junha/CovidSweeper#1]
<img width="1111" alt="Screen Shot 2020-03-25 at 11 01 51 AM" src="https://user-images.githubusercontent.com/5442091/77569905-2dba1980-6e88-11ea-9096-e4317b3415fa.png">

**Comment by a-qxin** [comment]
![bullet_error](https://user-images.githubusercontent.com/5442091/77573889-960bf980-6e8e-11ea-8dfa-498ad754fa2f.gif)

**Comment by park-junha** [comment]
![Screen Shot 2020-03-25 at 3 16 01 PM](https://user-images.githubusercontent.com/48537888/77590697-936bcd00-6eab-11ea-8805-551f28d990c6.png)
Reproducible on Safari

**Comment by park-junha** [comment]
![Screen Shot 2020-03-25 at 9 39 39 PM](https://user-images.githubusercontent.com/48537888/77610921-38ed6380-6ee1-11ea-9992-207fc773e1c8.png)

But not Firefox

**Comment by park-junha** [comment]
> ![Screen Shot 2020-03-25 at 3 16 01 PM](https://user-images.githubusercontent.com/48537888/77590697-936bcd00-6eab-11ea-8805-551f28d990c6.png)
> Reproducible on Safari

Also problematic on IE11 and Edge

**Comment by park-junha** [comment]
Fixed by #4
