### ISSUE TITLE
'pandemic stopped' at loss

### ISSUE THREAD

**Issue by a-qxin** [park-junha/CovidSweeper#2]
<img width="1246" alt="Screen Shot 2020-03-25 at 11 01 28 AM" src="https://user-images.githubusercontent.com/5442091/77570607-4b3bb300-6e89-11ea-952f-095f5b95a7d6.png">

**Comment by park-junha** [comment]
@a-qxin if you can replicate this issue again, can you press F12 on your browser, run `console.log(tilesToClick)`, and screenshot the output?

**Comment by a-qxin** [comment]
issue is actually just confusion with the counts not resetting at button press.
